// <auto-generated />
namespace Trabalho_2_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migracao_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracao_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206112314265_migracao_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
